package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'DeployToMavenCentral'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("DeployToMavenCentral")) {
    params {
        expect {
            password("env.GITHUB_ACCESS_TOKEN", "", label = "GitHub Access Token", display = ParameterDisplay.PROMPT)
        }
        update {
            password("env.GITHUB_ACCESS_TOKEN", "credentialsJSON:d40985a7-1757-4973-a7a9-d7c242badd13", label = "GitHub Access Token", display = ParameterDisplay.PROMPT)
        }
    }
}
