package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'GradleEnterpriseBuildConfigSamplesTestFrancois'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("GradleEnterpriseBuildConfigSamplesTestFrancois")
    name = "gradle-enterprise-build-config-samples-test-francois"
    url = "https://github.com/gradle/gradle-enterprise-build-config-samples"
    branch = "refs/heads/test-francois"
    branchSpec = "+:test-francois"
    authMethod = password {
        userName = "bot-teamcity"
        password = "credentialsJSON:61a1e766-a5a8-47ed-a5fb-af1e36f19aba"
    }
}))

