#!/bin/bash

current_dir=$PWD
maven_version=3.6.3

yellow='\033[1;33m'
nc='\033[0m'

if [ -n "$1" ]
then
  cd $1
fi  

echo -e "${yellow}Installing Maven wrapper${nc}"
mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=$maven_version

echo -e "${yellow}Customizing Maven wrapper script by adding a custom 'Wrapper' tag${nc}"
grep -q 'scan.tag.Wrapper' mvnw || sed -i '' $'s/^MAVEN_OPTS/&="-Dscan.tag.Wrapper $&"\\\n&/' mvnw

cd $current_dir

exit 0
