#!/bin/bash

current_dir=$PWD
custom_distribution_uri=https://github.com/gradle/gradle-enterprise-build-config-samples/raw/master/custom-maven-distribution/apache-maven-3.6.3-sample-1.0.0-bin.zip

yellow='\033[1;33m'
nc='\033[0m'

if [ -n "$1" ]
then
  cd $1
fi  

echo -e "${yellow}Updating applied Maven distribution${nc}"
sed -i '' -E 's|^(distributionUrl=).+|\1'"$custom_distribution_uri"'|' .mvn/wrapper/maven-wrapper.properties 

cd $current_dir

exit 0
