name: "Run and validate Maven execution with Gradle Enterprise extension"
description: "Run and validate Maven execution with Gradle Enterprise extension"

inputs:
    project-basedir:
        description: "Base directory of project to test"
        default: "None"
    LOG_MSG_EXTENSION_LOADED:
        description: "Log entry to grep in order to validate extension is loaded"
        default: "Build operation 'Gradle Enterprise mojo execution' completed"
    LOG_MSG_EXECUTION_FAILED:
        description: "Log entry to grep in order to detect extension's execution failed"
        default: "Error executing a GradleEnterpriseListener callback"

runs:
    using: "composite"
    steps:
        - name: Run Maven build using CCUD extension
          shell: bash
          run: |
              echo 'MAVEN_OUTPUT<<EOF' >> $GITHUB_ENV
              mvn -f ${{ inputs.project-basedir }}/pom.xml -X --batch-mode clean validate -Dgradle.scan.disabled=true >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
        - name: Validate extension loaded
          shell: bash
          run: |
              # Asserting that extension was loaded checking a log entry
              echo $MAVEN_OUTPUT | grep "${{ inputs.LOG_MSG_EXTENSION_LOADED }}"
        - name: Validate extension executed
          shell: bash
          run: |
              # Asserting that extension was run successfully checking absence of an error log entry
              echo $MAVEN_OUTPUT | grep -L "${{ inputs.LOG_MSG_EXECUTION_FAILED }}"


