name: Verify Convention Develocity Gradle Plugin (Nightly)
permissions:
  contents: read
  id-token: write
on:
  schedule:
    - cron: '0 4 * * *'
  push:
    paths:
      - ".github/workflows/convention-develocity-gradle-plugin-verification-nightly.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build Convention Develocity Gradle Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 'release-candidate'
          develocity-injection-enabled: true
          develocity-url: 'https://ge.solutions-team.gradle.com'
          develocity-plugin-version: '4.2.1'
          develocity-access-key: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
      - name: Configure Develocity Solutions instance
        working-directory: convention-develocity-gradle-plugin/plugins/gradle-5-or-newer/src/main/java/com/myorg
        run: sed -i 's/develocity-samples.gradle.com/ge.solutions-team.gradle.com/g' ConventionDevelocityGradlePlugin.java
      - name: Build with Gradle - Gradle 5 or newer
        working-directory: convention-develocity-gradle-plugin/plugins/gradle-5-or-newer
        run: gradle build publishToMavenLocal
      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: convention-develocity-gradle-plugin
          path: ~/.m2/repository/com/myorg
          
  verification:
    name: Verify Example Build for Gradle ${{ matrix.gradle-version }}
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-version: ['current', 'release-candidate', 'nightly']
        java-version: ['21']
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'temurin'
      - name: Set up Gradle ${{ matrix.gradle-version }}
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ matrix.gradle-version }}
      - name: Download plugin
        uses: actions/download-artifact@v5
        with:
          name: convention-develocity-gradle-plugin
          path: ~/.m2/repository/com/myorg
      - name: Verify example build
        id: build
        working-directory: convention-develocity-gradle-plugin/examples/gradle_6.9_and_later
        run: gradle build "-Dscan.value.gradle-version=${{ matrix.gradle-version }}" "-Dscan.value.java-version=${{ matrix.java-version }}"
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
      - name: Verify Build Scan published
        if: ${{ !steps.build.outputs.build-scan-url }}
        run: echo "::error ::No Build Scan published"; exit 1

  failure-notification:
    name: Matrix failure notification
    runs-on: ubuntu-latest
    needs:
      - build
      - verification
    if: failure()
    steps:
      - name: Get secrets
        uses: gradle/actions-internal/get-aws-secrets@v1
        with:
          role-to-assume: arn:aws:iam::992382829881:role/GHASecrets_develocity-build-config-samples_all
          secret-ids: |
            DV_SOLUTIONS_SCHEDULED_WORKFLOWS_WEBHOOK_URL,gha/develocity-build-config-samples/_all/dv_solutions_scheduled_workflows_webhook_url
      - name: Report scheduled workflow failure
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ env.DV_SOLUTIONS_SCHEDULED_WORKFLOWS_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload-templated: true
          payload: |
            {
              "workflow_name": "Verify Convention Develocity Gradle Plugin (Nightly)",
              "workflow_run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }